# Конфигурация для профиля "default"
server:
  port: 9092

spring:
  datasource:
    url: jdbc:h2:tcp:default
    driverClassName: org.h2.Driver
    username: default
    password: 1234
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.DB2Dialect



# Директория для загрузки файлов
# file.upload-dir: uploads  потом подключу, сейчас бесполезный конфиг, проект не развернут

# SMTP сервер для отправки почты
mail:
  host: smtp.gmail.com
  port: 587
  username: myemailexample@gmail.com
  password: mypassword
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true

# Конфигурация для профиля "test"
test:
  server:
    port: 8081

  spring:
    datasource:
      url: jdbc:h2:mem:testdb
      driverClassName: org.h2.Driver
      username: test
      password: 1234
    h2:
      console:
        enabled: true

    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate.dialect: org.hibernate.dialect.H2Dialect